CREATE TABLE AD_DESP_HOLMES (
  STATUS_LANC_HOLMES VARCHAR2(1) DEFAULT 'N' NOT NULL,
  EMPRESA NUMBER(2) NOT NULL,
  REVENDA NUMBER(2) NOT NULL,
  ESTABELECIMENTO VARCHAR2(14) NOT NULL,
  TIPO_TRANSACAO VARCHAR2(4),
  FORNECEDOR VARCHAR2(70) NOT NULL,
  CNPJ_CPF VARCHAR2(17),
  DEPARTAMENTO NUMBER(4),
  REQUISICAO VARCHAR2(100),
  CHASSI_PLACA VARCHAR2(300),
  NUMERO_NOTA_FISCAL NUMBER(38) NOT NULL,
  DATA_EMISSAO DATE NOT NULL,
  DATA_VENCIMENTO DATE NOT NULL,
  CHAVE_NFE VARCHAR2(300),
  NOTA_ORIGEM NUMBER(38),
  CONDICAO_PGTO NUMBER(4),
  COND_PGTO_DESC VARCHAR2(100),
  QTDE_PARC NUMBER(2),
  VALOR NUMBER(17, 2) NOT NULL,
  OBSERVACAO VARCHAR2(3000),
  PDF VARCHAR2(3000),
  PASTA_BOLETO VARCHAR2(3000),
  DATA_LANC_HOLMES DATE
)
  /*
  COMMENT ON COLUMN AD_DESP_HOLMES.STATUS_LANC_HOLMES IS 'Status do lançamento no holmes, default N para enviar após inserção';
  COMMENT ON COLUMN AD_DESP_HOLMES.ESTABELECIMENTO IS 'CNPJ da empresa/revenda para de-para com ID do holmes';
  COMMENT ON COLUMN AD_DESP_HOLMES.REQUISICAO IS 'Numero da requisicao gerada no envio para o Holmes (interna somente)';
  COMMENT ON COLUMN AD_DESP_HOLMES.CHASSI_PLACA IS 'para casos que precise ter registro de despesa para veiculo';
  COMMENT ON COLUMN AD_DESP_HOLMES.NOTA_ORIGEM IS 'Somente para CTE, necessário verificar transação específica';
  COMMENT ON COLUMN AD_DESP_HOLMES.OBSERVACAO IS 'Observação da descrição livre. Para transações P colocar Peças e para V colocar veiculos';
  */