CREATE TABLE AD_LOG_ERROR_HOLMES (
  EMPRESA NUMBER(6),
  REVENDA NUMBER(2),
  NUMERO_NOTA_FISCAL NUMBER(12),
  SERIE_NOTA_FISCAL VARCHAR2(5),
  CONTADOR NUMBER(5),
  TIPO_TRANSACAO VARCHAR2(4),
  ERROR VARCHAR2(4000),
  DATA_HORA DATE
);